version: '3'
services:
  #Nginx
  nginx_server:
    container_name: fire_server
    build: ./nginx_server
    volumes:
      - ../fire-app:/var/www/project
    ports:
      - "8000:80"
      - "6001:6001"
    tty: true
  #MYSQL
  db_mysql:
    container_name: fire_db
    build: ./mysql
    tty: true
    ports:
      - "43306:3306"
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root@secret123

